---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: citadel
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: os-release
    properties:
      NAME: Citadel
      PRETTY_NAME: Citadel
      DEFAULT_HOSTNAME: citadel

  - type: files
    files:
      - source: system
        destination: /

  - from-file: common/cleanup.yml
  - from-file: common/base.yml
  - from-file: common/develop.yml
  - from-file: common/gaming.yml
  - from-file: common/mango.yml
  - from-file: common/dotfiles.yml

  - from-file: common/kernel.yml

  - type: signing
